### ISSUE TITLE
Am I gay?

### ISSUE THREAD

**Issue by celtare21** [King-Kernel/KingKernel-floral#3]
I want the kernel to display a message on boot telling me if I'm gay or not. Thank you.

**Comment by baalajimaestro** [comment]
You need some help.

**Comment by celtare21** [comment]
I need jesus

**Comment by celtare21** [comment]
Can the kernel give me jesus?

**Comment by baalajimaestro** [comment]
Jesus is dead, you may proceed into the darkness.

**Comment by kingbri1** [comment]
Looks like nobody can help you, closing this issue
